[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[build]
  functions = "web/functions"
  publish = "/web/public"

[dev]
  functions = "web/functions"
  publish = "/web/public"

# Inject ENV vars for lambdas since they don't get overridden by
# `[context.xxx.environemnt]` vars in the TOML files
[context.branch-deploy]
  command = """\
  export GATSBY_STRIPE_PUBLISHABLE_KEY=pk_test_vQgx6A3eI1OZAkiBb90F6xyF && \
  export GATSBY_STRIPE_SECRET_KEY=sk_test_1x5inX2fR7wEopNNIfKTPRy3 && \
  export SITE_URL=https://staging.earth6r.com/ && \
  export EMAIL_USERNAME=loma.trantow78@ethereal.email && \
  export EMAIL_PASSWORD=pSff3584K3u39TtGvD && \
  export EMAIL_HOST=smtp.ethereal.email && \
  export EMAIL_PORT=587 && \
  export BITPAY_POS_TOKEN=2GW2QCUEU8Vm9aNzTCZwhKSXPH2c3XcQGZdbN3dbWYUv && \
  export BITPAY_API_URL=https://test.bitpay.com && \
  ./node_modules/.bin/babel --plugins transform-inline-environment-variables web/functions/create-checkout.js -o web/functions/create-checkout.js && \
  ./node_modules/.bin/babel --plugins transform-inline-environment-variables web/functions/mailers/send.js -o web/functions/mailers/send.js && \
  ./node_modules/.bin/babel --plugins transform-inline-environment-variables web/functions/handle-stripe-purchase.js -o web/functions/handle-stripe-purchase.js && \
  ./node_modules/.bin/babel --plugins transform-inline-environment-variables web/functions/mailers/handle-bitpay-purchase.js -o web/functions/mailers/handle-bitpay-purchase.js && \
  npm run build-web\
"""

[context.branch-deploy.environment]
  GATSBY_STRIPE_PUBLISHABLE_KEY="pk_test_vQgx6A3eI1OZAkiBb90F6xyF"
  GATSBY_STRIPE_SECRET_KEY="sk_test_1x5inX2fR7wEopNNIfKTPRy3"
  SITE_URL="https://staging.earth6r.com/"